### ISSUE TITLE
fails to build with rustc 1.28.0-nightly (952f344cd 2018-05-18)

### ISSUE THREAD

**Issue by alsam** [cogciprocate/ocl#109]
Hello,
fails with the message:
```rust
   Compiling opencl_2_1 v0.1.0 (file:///.../ocl/ocl/examples/opencl_2_1)
error[E0369]: binary operation `==` cannot be applied to type `std::result::Result<std::string::String, ocl::<unnamed>::Error>`
  --> ocl/examples/opencl_2_1/src/main.rs:34:61
   |
34 |     let platform = Platform::list().into_iter().find(|plat| plat.name() == PLATFORM_NAME)
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `std::result::Result<std::string::String, ocl::<unnamed>::Error>`

error[E0599]: no method named `clone` found for type `std::result::Result<ocl::Device, ocl::Error>` in the current scope
  --> ocl/examples/opencl_2_1/src/main.rs:44:25
   |
44 |         .devices(device.clone())
   |                         ^^^^^
   |
   = note: the method `clone` exists but the following trait bounds were not satisfied:
           `std::result::Result<ocl::Device, ocl::Error> : std::clone::Clone`

error[E0277]: the trait bound `ocl::builders::DeviceSpecifier: std::convert::From<std::result::Result<ocl::Device, ocl::Error>>` is not satisfied
  --> ocl/examples/opencl_2_1/src/main.rs:50:10
   |
50 |         .devices(device)
   |          ^^^^^^^ the trait `std::convert::From<std::result::Result<ocl::Device, ocl::Error>>` is not implemented for `ocl::builders::DeviceSpecifier`
   |
   = help: the following implementations were found:
             <ocl::builders::DeviceSpecifier as std::convert::From<&'a ocl::Device>>
             <ocl::builders::DeviceSpecifier as std::convert::From<&'a [ocl::Device]>>
             <ocl::builders::DeviceSpecifier as std::convert::From<&'a [usize]>>
             <ocl::builders::DeviceSpecifier as std::convert::From<&'a std::vec::Vec<usize>>>
           and 6 others
   = note: required because of the requirements on the impl of `std::convert::Into<ocl::builders::DeviceSpecifier>` for `std::result::Result<ocl::Device, ocl::Error>`

error[E0308]: mismatched types
  --> ocl/examples/opencl_2_1/src/main.rs:51:13
   |
51 |         .il(il_src)
   |             ^^^^^^
   |             |
   |             expected &[u8], found struct `std::vec::Vec`
   |             help: consider borrowing here: `&il_src`
   |
   = note: expected type `&[u8]`
              found type `std::vec::Vec<u8>`

error: aborting due to 4 previous errors

Some errors occurred: E0277, E0308, E0369, E0599.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `opencl_2_1`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Thanks

**Comment by c0gent** [comment]
11d630397ab87cd22c8672cc91e44d0d02dc5b0d fixes the example so that it compiles.

I'm having problems actually running the example on my OpenCL 2.1 capable machine. Getting the 'process didn't exit successfully' error. I only have windows loaded on that machine so I can't test on linux at the moment. I haven't played with this example in a long time. I may be forgetting something.

Please let me know if you have any luck.

**Comment by alsam** [comment]
It's ok now, checked with up to date `rustc 1.28.0-nightly (71e87be38 2018-05-22)`

```sh
...
   Compiling failure v0.1.1
   Compiling num v0.1.42
   Compiling futures-async-runtime v0.2.1 (https://github.com/rust-lang-nursery/futures-rs#6810513e)
   Compiling chrono v0.2.25
   Compiling jpeg-decoder v0.1.14
   Compiling futures v0.2.1 (https://github.com/rust-lang-nursery/futures-rs#6810513e)
   Compiling image v0.19.0
   Compiling ocl v0.18.0 (file:///home/spike/work/github/ocl/ocl)
   Compiling images v0.2.0 (file:///home/spike/work/github/ocl/ocl/examples/images)
   Compiling ocl-example-rgb2gray v0.2.0 (file:///home/spike/work/github/ocl/ocl/examples/images_safe_clamp)
   Compiling opencl_2_1 v0.1.0 (file:///home/spike/work/github/ocl/ocl/examples/opencl_2_1)
   Compiling ocl-proto v0.0.1 (file:///home/spike/work/github/ocl/ocl/examples/proto)
   Compiling ocl-extras v0.1.0 (file:///home/spike/work/github/ocl/ocl/ocl-extras)
    Finished dev [unoptimized + debuginfo] target(s) in 28.86s
```

Thanks you! I'll close the bug.
