### ISSUE TITLE
Compilation fails on Windows 10

### ISSUE THREAD

**Issue by stefanhoelzl** [cogciprocate/ocl#162]
I tried to compile a crate using `ocl` but it Fails on Windows 10
My `main.rs`
```rust
extern crate ocl
fn main() {
}
```
ocl Version: `1.9.3`
rustc Version: `rustc 1.39.0-nightly (b9de4ef89 2019-09-03)`

```bash
D:\temp\dexter>cargo run --release
   Compiling winapi v0.3.7
   Compiling syn v0.15.44
   Compiling synstructure v0.10.2
   Compiling rand v0.4.6
   Compiling num-bigint v0.1.44
   Compiling num-rational v0.1.42
   Compiling num v0.1.42
   Compiling ocl-core-vector v0.1.0
   Compiling failure_derive v0.1.5
   Compiling failure v0.1.5
   Compiling ocl-core v0.11.2
   Compiling ocl v0.19.3
error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\platform.rs:190:9
    |
190 |         format!("{}", p)
    |         ^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\device.rs:551:9
    |
551 |         format!("{}", d)
    |         ^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\program.rs:363:31
    |
363 |                     opts.push(format!("-D {}={}", ident, val))
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\program.rs:367:31
    |
367 |                     opts.push(format!("-I {}", path))
    |                               ^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\program.rs:393:47
    |
393 |                     strings.push(CString::new(format!("#define {}  {}\n", ident, val)
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
  --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\buffer.rs:20:13
   |
20 |           Err(format!("ocl::Buffer::enq(): Offset out of range. \
   |  _____________^
21 | |             (mem_len: {}, data_len: {}, offset: {}", mem_len, data_len, offset).into())
   | |_______________________________________________________________________________^ could not find `format_args` in `core`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
    --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\buffer.rs:2042:24
     |
2042 |               return Err(format!("Buffer::create_sub_buffer: Origin ({:?}) is outside of the \
     |  ________________________^
2043 | |                 dimensions of the source buffer ({:?}).", offset, buffer_len).into());
     | |_____________________________________________________________________________^ could not find `format_args` in `core`
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
    --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\buffer.rs:2047:24
     |
2047 |               return Err(format!("Buffer::create_sub_buffer: Sub-buffer region (origin: '{:?}', \
     |  ________________________^
2048 | |                 len: '{:?}') exceeds the dimensions of the source buffer ({:?}).",
2049 | |                 offset, len, buffer_len).into());
     | |________________________________________^ could not find `format_args` in `core`
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\pro_que.rs:430:32
    |
430 |                       return Err(format!("Invalid number of devices specified ({}). Each 'ProQue' \
    |  ________________________________^
431 | |                         can only be associated with a single device. Use 'Context', 'Program', and \
432 | |                         'Queue' separately for multi-device configurations.",
433 | |                         device_list.len()).into());
    | |__________________________________________^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\spatial_dims.rs:331:28
    |
331 |       val.to_usize().expect(&format!("Unable to convert the value '{:?}' into a 'SpatialDims'. \
    |  ____________________________^
332 | |         Dimensions must have positive values.", val))
    | |____________________________________________________^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
  --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\mod.rs:90:17
   |
90 |                 format!("{:?}", Status::from_i32(event_status))
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
  --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\standard\mod.rs:92:17
   |
92 |                 format!("{:?}", CommandExecutionStatus::from_i32(event_status))
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\error.rs:100:21
    |
100 |         let debug = format!("{:?}", err);
    |                     ^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\error.rs:101:23
    |
101 |         let display = format!("{}", err);
    |                       ^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\error.rs:103:13
    |
103 |             format!("{}: '{}'", debug, display))) }
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> C:\Users\Stefan Hölzl\.cargo\registry\src\github.com-1ecc6299db9ec823\ocl-0.19.3\src\async\order_lock.rs:642:26
    |
642 |                         &format!("FutureGuard::poll_upgrade: Status: {:?}", status));
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 16 previous errors

For more information about this error, try `rustc --explain E0433`.
error: Could not compile `ocl`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by dignifiedquire** [comment]
Same issue here, on both Ubuntu and macOS. 

```
rustc 1.39.0-nightly (521d78407 2019-08-25)
```

**Comment by aabizri** [comment]
I had the same error, working on `stable` (`rustc 1.37.0 (eae3437df 2019-08-13)` but not on `nightly` (don't have the version as I updated).

This now works for me on (`rustc 1.39.0-nightly (96d07e0ac 2019-09-15)`).
